name: image_editor_pro
description: Image Editor  Plugin  for Both Android and IOS
version: 0.0.1
author: zeeshux7860,theindianappguy
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  zoom_widget: ^0.1.3
  font_awesome_flutter: ^8.7.0
  image_picker: ^0.7.4
  path_provider: ^2.0.2
  image_gallery_saver: ^1.2.2
  permission_handler: ^4.2.0+hotfix.3
  screenshot: ^1.1.0
  signature: ^4.0.0
  flutter_colorpicker: ^0.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: zeeshux7860.theindianappguy.image_editor_pro
    pluginClass: ImageEditorProPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/capa25463.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
